# Generated by Django 2.2.4 on 2019-09-12 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('discordURL', models.URLField()),
                ('videoURL', models.URLField()),
                ('category', models.CharField(choices=[('HUN', 'Bounty Hunting'), ('ENG', 'Engineering'), ('EXP', 'Exploration'), ('FRE', 'Freelancing'), ('INF', 'Infiltration'), ('PIR', 'Piracy'), ('RES', 'Resources'), ('SCO', 'Scouting'), ('SEC', 'Security'), ('SMU', 'Smuggling'), ('SOC', 'Social'), ('TRD', 'Trading'), ('TRA', 'Training'), ('TRN', 'Transport'), ('XXX', 'Top Secret')], default='FRE', max_length=3)),
                ('location', models.CharField(max_length=150)),
                ('feature_image', models.URLField()),
                ('mission_date', models.DateTimeField()),
                ('mission_status', models.CharField(choices=[('ACT', 'Active'), ('FAI', 'Failed'), ('SUC', 'Successful')], default='ACT', max_length=3)),
                ('briefing', models.TextField()),
                ('debriefing', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended_users', models.ManyToManyField(related_name='attended_users', to=settings.AUTH_USER_MODEL)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commander', to=settings.AUTH_USER_MODEL)),
                ('rsvp_users', models.ManyToManyField(related_name='rsvp_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
