# Generated by Django 2.2.4 on 2019-09-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='briefing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='debriefing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='discordURL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='feature_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='videoURL',
            field=models.URLField(blank=True),
        ),
    ]
