# Generated by Django 2.2.4 on 2019-09-12 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_auto_20190912_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='attended_users',
            field=models.ManyToManyField(blank=True, related_name='attended_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mission',
            name='rsvp_users',
            field=models.ManyToManyField(blank=True, related_name='rsvp_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
