# Generated by Django 2.2.4 on 2019-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('MEM', 'Member'), ('AFF', 'Affiliate')], default='AFF', max_length=3),
        ),
    ]
